const { Client } = require('discord.js');
const intents = require('./intents');
const ready = require('./on/ready');
const settings = require('../../config/settings.json');

const apiRequest = require('./on/apiRequest');
const apiResponse = require('./on/apiResponse');
const debug = require('./on/debug');
const error = require('./on/error');
const interactionCreate = require('./on/interactionCreate');
const messageCreate = require('./on/messageCreate');
const messageDelete = require('./on/messageDelete');
const messageReactionAdd = require('./on/messageReactionAdd');
const messageReactionRemove = require('./on/messageReactionRemove');
const messageReactionRemoveEmoji = require('./on/messageReactionRemoveEmoji');
const messageUpdate = require('./on/messageUpdate');
// const presenceUpdate = require('./on/presenceUpdate');
const roleUpdate = require('./on/roleUpdate');
const shardDisconnect = require('./on/shardDisconnect');
const shardError = require('./on/shardError');
const shardReady = require('./on/shardReady');
const shardReconnecting = require('./on/shardReconnecting');
const shardResume = require('./on/shardResume');
const threadMemberUpdate = require('./on/threadMemberUpdate');
const threadUpdate = require('./on/threadUpdate');
const typingStart = require('./on/typingStart');
const userUpdate = require('./on/userUpdate');
const voiceStateUpdate = require('./on/voiceStateUpdate');
const warn = require('./on/warn');
const webhookUpdate = require('./on/webhookUpdate');

const client = new Client({ intents });

client.on('apiRequest', apiRequest);
client.on('apiResponse', apiResponse);
client.on('debug', debug);
client.on('error', error);
client.on('interactionCreate', interactionCreate);
client.on('messageCreate', messageCreate);
client.on('messageDelete', messageDelete);
client.on('messageReactionAdd', messageReactionAdd);
client.on('messageReactionRemove', messageReactionRemove);
client.on('messageReactionRemoveEmoji', messageReactionRemoveEmoji);
client.on('messageUpdate', messageUpdate);
// client.on('presenceUpdate', presenceUpdate);
client.on('ready', () => ready(client));
client.on('roleUpdate', roleUpdate);
client.on('shardDisconnect', shardDisconnect);
client.on('shardError', shardError);
client.on('shardReady', shardReady);
client.on('shardReconnecting', shardReconnecting);
client.on('shardResume', shardResume);
client.on('threadMemberUpdate', threadMemberUpdate);
client.on('threadUpdate', threadUpdate);
client.on('typingStart', typingStart);
client.on('userUpdate', userUpdate);
client.on('voiceStateUpdate', voiceStateUpdate);
client.on('warn', warn);
client.on('webhookUpdate', webhookUpdate);

client.login(settings.token);
